# For Github Actions only
PROJECT_NAME_TEST:
  target: dev
  outputs:
    dev:
      account: SNOWFLAKE_ACCOUNT_TEST
      database: SNOWFLAKE_DATABASE_TEST
      password: "{{ env_var('SNOW_PASSWORD') }}"
      role: SNOWFLAKE_ROLE_TEST
      schema: TECH
      threads: 1
      type: snowflake
      user: SNOWFLAKE_USER_TEST
      warehouse: SNOWFLAKE_WAREHOUSE_TEST
    prod:
      account: SNOWFLAKE_ACCOUNT_TEST
      database: SNOWFLAKE_DATABASE_TEST
      password: "{{ env_var('SNOW_PASSWORD') }}"
      role: SNOWFLAKE_ROLE_TEST
      schema: BRONZE
      threads: 1
      type: snowflake
      user: SNOWFLAKE_USER_TEST
      warehouse: SNOWFLAKE_WAREHOUSE_TEST
