name: Setup Snowflake environment
run-name: Setup Snowflake environment triggered by @${{ github.actor }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    setup-github-variables:
        name: Set up Github Action variables
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: gh variable set -f .github/.env
    setup-dbt:
        name: Update DBT project files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                yq 'with(. ; .profile = '${{vars.project_name}} | .name = '${{vars.project_name}}')'

            # - uses: mikefarah/yq@master
            #   id: project-name
            #   with:
            #     cmd: yq '.project-name' .github/config.yml
        # Update dbt files (dbt_project.yml, profiles.yml, schema.yml)
    # setup-snowflake:
        # Check if user is account admin ?
        # Create database, schema, roles
        # Assign roles to schema/db