name: Setup Snowflake environment
run-name: Setup Snowflake environment triggered by @${{ github.actor }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    setup-dbt:
        name: Update DBT project files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: yq '.' .github/env.yml -os
            - run: |
                for i in $(yq '.' .github/env.yml -os); do
                    "$i" >> $GITHUB_ENV
                done
            - run: echo ${{env.project_name}}
            - run: |
                echo ${{env.project_name}}
                yq 'with(. ; .profile = '${{env.project_name}}' | .name = '${{env.project_name}}')' dbt_project.yml

            # - uses: mikefarah/yq@master
            #   id: project-name
            #   with:
            #     cmd: yq '.project-name' .github/config.yml
        # Update dbt files (dbt_project.yml, profiles.yml, schema.yml)
    # setup-snowflake:
        # Check if user is account admin ?
        # Create database, schema, roles
        # Assign roles to schema/db