name: Setup Snowflake environment
run-name: Setup Snowflake environment triggered by @${{ github.actor }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    get-env-settings:
        name: Get environment settings
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Env variables
              id: get-env
              run: |
                while read -r i;do
                    echo "$i" >> $GITHUB_OUTPUT
                done <<< "$(yq '.' .github/env.yml -os)"
    setup-dbt:
        name: Update DBT project files
        runs-on: ubuntu-latest
        needs: get-env-settings
        steps:
            - name: Update dbt_project.yml
              run: yq -i 'with(. ; .profile = env(PROJECT_NAME) | .name = env(PROJECT_NAME))' dbt_project.yml
            - run: cat dbt_project.yml
            - name: Update profiles.yml
              run: |
                yq -i '(.template_profile_name | key) = env(PROJECT_NAME)' profiles.yml
                yq -i 'with(.[env(PROJECT_NAME)].outputs[]; .account = env(SNOWFLAKE_ACCOUNT) | .database = env(SNOWFLAKE_DATABASE) | .role = env(SNOWFLAKE_ROLE) | .user = env(SNOWFLAKE_USER) | .warehouse = env(SNOWFLAKE_WAREHOUSE))' profiles.yml
            - run: cat profiles.yml
            - name: Update models/schema.yml
              run: yq -i 'with(.sources.[]; .database = env(SNOWFLAKE_DATABASE))' models/schema.yml
            - run: cat models/schema.yml
            # Add git commit
    setup-snowflake:
        name: Setup Snowflake
        runs-on: ubuntu-latest
        needs: get-env-settings
        steps:
            - run: echo ${{ needs.get-env-settings.outputs }}
            - run: echo ${{ needs.get-env-settings.outputs.PROJECT_NAME }}
        # Check if user is account admin ?
        # Create database, schema, roles
        # Assign roles to schema/db