name: Setup Snowflake environment
run-name: Setup Snowflake environment triggered by @${{ github.actor }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    setup-dbt:
        name: Update DBT project files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                yq e 'keys' .github/config.yml | while read -r key; do
                value=$(yq e ".${key}" .github/config.yml)
                echo "${key}=${value}" >> $GITHUB_ENV
                done
              name: Export config file to env
            - run: echo $snowflake_account
            - run: export -p
            - run: env




            # - uses: mikefarah/yq@master
            #   id: project-name
            #   with:
            #     cmd: yq '.project-name' .github/config.yml
            # - uses: mikefarah/yq@master
            #   id: snowflake-account
            #   with:
            #     cmd: yq '.snowflake-account' .github/config.yml
        # Update dbt files (dbt_project.yml, profiles.yml, schema.yml)
    # setup-snowflake:
        # Check if user is account admin ?
        # Create database, schema, roles
        # Assign roles to schema/db