name: Setup Snowflake environment
run-name: Setup Snowflake environment triggered by @${{ github.actor }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    setup-dbt:
        name: Update DBT project files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Env variables
              run: |
                while read -r i;do
                    echo "$i" >> $GITHUB_ENV
                done <<< "$(yq '.' .github/env.yml -os)"
            - run: yq 'with(. ; .profile = 'env(project_name)' | .name = 'env(project_name)')' dbt_project.yml
            - run: cat dbt_project.yml
            - run: |
                yq '(.template_profile_name | key) = "env(project_name)"' profiles.yml
                yq 'with(.[env(project_name)].outputs.dev; .account = "env(snowflake_account)" | .database = "env(snowflake_database)")' profiles.yml
            - run: cat profiles.yml
        # Update dbt files (dbt_project.yml, profiles.yml, schema.yml)
    # setup-snowflake:
        # Check if user is account admin ?
        # Create database, schema, roles
        # Assign roles to schema/db